name: Create a comment on a newly created issue

on:
  issues:
    types:
      - opened


jobs:
  comment-with-actions:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: "dumb github context"
        run: echo '${{ toJSON(github.event)}}' | jq
        shell: bash

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With github **Markdown** sparkles:
            - Created by [create-or-updat-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'