name: Create a comment on a newly created issue

on:
  issues:
    types:
      - opened


jobs:
  comment-with-actions:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: "dumb github context"
        run: echo '${{ toJSON(github.event)}}' | jq
        shell: bash

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With github **Markdown** :sparkles:
            - Created by [create-or-updat-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

  comment-with-api:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: check user login
        run: echo ${{ github.event.user.login }}
        shell: bash

      - name: Create comments with api
        run: |
          gh api -X POST \
            https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments\
            -f body='
              Comment but from api call not action
            '
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}